### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by dietmarw** [droberg/Modelica-MVEM#2]
In order that your library can be found and managed by the [impact package manager](https://impact.github.io) you need to tag a release. For this you should follow [Semantic Version](http://semver.org/) to also allow impact to "understand" your releases and dependencies. 

To make it simple I suggest you simply tag your current status `v1.0.0` (the "v" in front if the semantic version is a common convention for tag names)

I.e., 
``` 
git tag v1.0.0 -m"Tagging orginal release of 2013-10-21"
git push --tags origin v1.0.0
```
Best do that after having accepted the PR #1

**Comment by droberg** [comment]
Thanks, this should be taken care of now. 
Please let me know if I screwed it up somehow =)

**Comment by dietmarw** [comment]
:+1:
