### ISSUE TITLE
Error using within

### ISSUE THREAD

**Issue by tbeu** [droberg/Modelica-MVEM#4]
```
Error while loading the file g:\Libraries\Modelica-MVEM\MVEMLib\Basic\package.mo.
The environment given after "within" "MVEMLib" does not match the actual environment "ROOT" (g:\Libraries\Modelica-MVEM\MVEMLib\Basic\package.mo).

Message: Modelica.WithinError

Error while loading the file g:\Libraries\Modelica-MVEM\MVEMLib\Engines\package.mo.
The environment given after "within" "MVEMLib" does not match the actual environment "ROOT" (g:\Libraries\Modelica-MVEM\MVEMLib\Engines\package.mo).

Message: Modelica.WithinError

Error while loading the file g:\Libraries\Modelica-MVEM\MVEMLib\Examples\package.mo.
The environment given after "within" "MVEMLib" does not match the actual environment "ROOT" (g:\Libraries\Modelica-MVEM\MVEMLib\Examples\package.mo).

Message: Modelica.WithinError
```

**Comment by droberg** [comment]
This looks wierd, what tool are you using?
How are you loading the package?

**Comment by tbeu** [comment]
I used SimulationX 3.7.1 but the problem should be obvious with any other tool that is strict on within.

Anyway, it is easy to fix. Instead of the empty namespace after within add the proper one.

**Comment by droberg** [comment]
I see what you mean, I'll make a patch as soon as I can try it out so that I don't mess things up.

Thanks.

**Comment by tbeu** [comment]
Thanks. I was just too lazy to prepare a PR myself.

**Comment by droberg** [comment]
Now I don't see it again, could you please advice?

The package itself is in the directory "MVEMLib" (Not in Modelica-MVEM). The base "package.mo" contains an empty "within ;". This is correct according to Modelica specification 3.3 p.171. The other specificed "within MVEMLib.xxx ; " etc. All seems correct to me, but hey, it's after bed-time for my kids...

Does it work if  you put MVEMLib directory direct into you libraries directory? I  checked with for example  PowerSystems lib (also on github and supported by MSA ) and there a doubling of directory/package dirs are used. (PowerSystem is both the name of the package, the Github project, and the first package dir inside the project)

**Comment by tbeu** [comment]
I tried to reproduce but am not able. Sorry for the confusion.
