### ISSUE TITLE
Unsuitable type class

### ISSUE THREAD

**Issue by tbeu** [droberg/Modelica-MVEM#6]
MVEMLib.Basic.Restrictions.Compressible (and many more) is of type `class` but needs to be changed to a specialized class `model`.

**Comment by droberg** [comment]
Hmm.. I was just looking at the Modelica specification 3.3 which states that the specialized class "models" is "Identical to class, the basic class concept, i.e., no restrictions and no enhancements." 

I guess I can change my code to use "model" if it clarifies anything or makes the library easier to use in some tools. 

Comments?

**Comment by droberg** [comment]
If I didn't make a mistake when fixing issue #5 this is now also fixed.

Closing
